// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.client.common.entity;

public interface AccessInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.client.common.entity.AccessInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.dkohut.bookchat.client.common.entity.AccessEnum access = 1;</code>
   */
  int getAccessValue();
  /**
   * <code>.com.dkohut.bookchat.client.common.entity.AccessEnum access = 1;</code>
   */
  com.dkohut.bookchat.client.common.entity.AccessEnum getAccess();
}
