// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.common.entity;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_LoginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022!com.dkohut.bookchat" +
      ".common.entity\032\021BookService.proto\"P\n\004Use" +
      "r\022\n\n\002id\030\001 \001(\005\022\r\n\005login\030\002 \001(\t\022\020\n\010password" +
      "\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\"/\n\014L" +
      "oginMessage\022\r\n\005login\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t2\335\001\n\013UserService\022k\n\014registration\022\'.c" +
      "om.dkohut.bookchat.common.entity.User\0322." +
      "com.dkohut.bookchat.common.entity.Respon" +
      "seMessage\022a\n\005login\022/.com.dkohut.bookchat" +
      ".common.entity.LoginMessage\032\'.com.dkohut",
      ".bookchat.common.entity.UserB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dkohut.bookchat.common.entity.BookServiceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_dkohut_bookchat_common_entity_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dkohut_bookchat_common_entity_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_User_descriptor,
        new java.lang.String[] { "Id", "Login", "Password", "Name", "Email", });
    internal_static_com_dkohut_bookchat_common_entity_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dkohut_bookchat_common_entity_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_LoginMessage_descriptor,
        new java.lang.String[] { "Login", "Password", });
    com.dkohut.bookchat.common.entity.BookServiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
